fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0 #v4.1.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: forbid-new-submodules
    - id: check-added-large-files
    - id: fix-byte-order-marker
    - id: no-commit-to-branch # Prevent commits on master directly
      args:
      - --branch
      - main
    - id: trailing-whitespace

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5 # v1.1.13
    hooks:
      - id: forbid-crlf
      - id: remove-crlf

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0 #v2.1.16
    hooks:
      - id: forbid-binary
        exclude: \.png$
      - id: shellcheck # Needs shellcheck: https://github.com/koalaman/shellcheck
      - id: shfmt # Needs shfmt: https://github.com/mvdan/sh/releases

    # Internal checks
  - repo: local
    hooks:
      - id: angular_commit_message
        name: Check angular commit message style
        description: Check commit messages are following angular commit style
        entry: pre_commit_hooks/angular_commit_msg.py
        language: script
        stages: [commit-msg]
